name: docker build and push
on:
  schedule:
    - cron: '30 1 * * *'

env:
  ECR_REGISTRY: 999999999999.dkr.ecr.eu-west-2.amazonaws.com
  ECR_REPOSITORY: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: docker test build
      run: |
        docker build -t my-build \
        --build-arg TERRAGRUNT_VERSION=`cat ../../.terragrunt-version` \
        --build-arg TERRAFORM_VERSION=`cat ../../.terraform-version` \
        .

    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDDHH

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ECR_PUSH_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ECR_PUSH_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ steps.current-time.outputs.formattedTime }}
      run: |
        # Build a docker container and push it to ECR
        cd docker/terragrunt-github-runner/
        docker tag \
          my-build ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
