name: slack notification on master build
on:
  workflow_run:
    workflows:
      - terragrunt apply
    branches:
      - main
    types:
      - completed

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        id: slack
        uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: ${{ github.event.workflow_run.conclusion }}
          channel: '#terragrunt'
